GET http://localhost:3333/
###

PUT http://localhost:3333/flutterqrs/1
content-type: application/json

{
  "url": "https://media1.giphy.com/media/0Wzkc9iirQ4ZI7JoaD/giphy.gif?cid=790b7611278234535d01794f7a5b45683ac35421dfe4b97b&rid=giphy.gif&ct=g"
}
###
PUT http://localhost:3333/reactqrs/1
content-type: application/json

{
  "url": "https://media1.giphy.com/media/0Wzkc9iirQ4ZI7JoaD/giphy.gif?cid=790b7611278234535d01794f7a5b45683ac35421dfe4b97b&rid=giphy.gif&ct=g"
}
###


GET http://localhost:3333/animations/
###
GET http://localhost:3333/animations/1
###
DELETE http://localhost:3333/animations/1
###
POST http://localhost:3333/animations
content-type: application/json

{
  "url": "http://xxxxxxxxxxxxxxxxx",
  "react": false,
  "flutter": false
}
###
PUT http://localhost:3333/animations/1 HTTP/1.1
content-type: application/json

{
  "url": "https://media1.giphy.com/media/0Wzkc9iirQ4ZI7JoaD/giphy.gif?cid=790b7611278234535d01794f7a5b45683ac35421dfe4b97b&rid=giphy.gif&ct=g",
  "react": false,
  "flutter": false
}
###

PUT http://localhost:3333/update